# Generated by Django 6.0.7 on 2026-07-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Remote_User", "0007_clientposts_model_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="detect_fraudulent_cc_transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Fid", models.CharField(max_length=3000)),
                ("Trans_Date", models.CharField(max_length=3000)),
                ("CC_No", models.CharField(max_length=3000)),
                ("CC_type", models.CharField(max_length=3000)),
                ("Trans_Type", models.CharField(max_length=3000)),
                ("Amount", models.CharField(max_length=3000)),
                ("Firstname", models.CharField(max_length=3000)),
                ("Lastname", models.CharField(max_length=3000)),
                ("Gender", models.CharField(max_length=3000)),
                ("Age", models.CharField(max_length=3000)),
                ("lat", models.CharField(max_length=3000)),
                ("lon", models.CharField(max_length=3000)),
                ("Transid", models.CharField(max_length=3000)),
                ("Prediction", models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name="detection_accuracy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("names", models.CharField(max_length=300)),
                ("ratio", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="detection_ratio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("names", models.CharField(max_length=300)),
                ("ratio", models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name="clientposts_model",
            name="userId",
        ),
        migrations.DeleteModel(
            name="review_Model",
        ),
        migrations.AlterField(
            model_name="clientregister_model",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="clientregister_model",
            name="phoneno",
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name="ClientPosts_Model",
        ),
    ]
